package Views;

import Entities.User;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import java.util.Calendar;
import java.text.SimpleDateFormat;

/**
 *
 * @author dehr2
 */
public class VwMenu extends javax.swing.JFrame {
    
    private User currentUser;
    
    public VwMenu(User currentUser) throws InterruptedException {
        this.currentUser = currentUser;
        initComponents();
        txtViewPanel.setText("Menú Principal");
        Timer timer = new Timer(1, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateTimeAndDate();
                //System.out.println("Ancho -> " + Toolkit.getDefaultToolkit().getScreenSize().getWidth());
            }
        });
        timer.start();
        Thread.sleep(1);
        
        panelSwitch(new VwMainMenu(currentUser));
    }
    
    private void updateTimeAndDate() {
        // Get the current time and format it
        Calendar calendar = Calendar.getInstance();
        SimpleDateFormat timeFormatter = new SimpleDateFormat("HH:mm:ss");
        String time = timeFormatter.format(calendar.getTime());
        
        // Get the current date and format it
        SimpleDateFormat dateFormatter = new SimpleDateFormat("EEE, MMM dd, yyyy");
        String date = dateFormatter.format(calendar.getTime());

        // Update the time and date labels
        timeLabel.setText(time);
        dateLabel.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnPrincipalMenu = new javax.swing.JPanel();
        btnLogOut = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtViewPanel = new javax.swing.JLabel();
        labMode = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnHelp = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        viewsSwitch = new javax.swing.JTabbedPane();
        mainMenu = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión - Taller Mecánico \"Camilo\"");
        setExtendedState(6);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnPrincipalMenu.setBackground(new java.awt.Color(65, 80, 87));
        jpnPrincipalMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jpnPrincipalMenu.setDoubleBuffered(false);
        jpnPrincipalMenu.setPreferredSize(new Dimension(java.awt.Toolkit.getDefaultToolkit().getScreenSize().width, 70));

        btnLogOut.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgLogOut.png"))); // NOI18N
        btnLogOut.setText("Cerrar Sesión");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(247, 150, 64));

        txtViewPanel.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        txtViewPanel.setForeground(new java.awt.Color(255, 255, 255));
        txtViewPanel.setText("Menú Principal");

        labMode.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        labMode.setForeground(new java.awt.Color(255, 255, 255));
        labMode.setText("Administración");

        jLabel3.setFont(new java.awt.Font("Gadugi", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("|");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtViewPanel)
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewPanel)
                    .addComponent(jLabel3)
                    .addComponent(labMode))
                .addGap(19, 19, 19))
        );

        btnGoBack.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnGoBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/imgMainMenu.png"))); // NOI18N
        btnGoBack.setText("Menú Principal");
        btnGoBack.setEnabled(false);
        btnGoBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBackActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tituloTaller.png"))); // NOI18N

        javax.swing.GroupLayout jpnPrincipalMenuLayout = new javax.swing.GroupLayout(jpnPrincipalMenu);
        jpnPrincipalMenu.setLayout(jpnPrincipalMenuLayout);
        jpnPrincipalMenuLayout.setHorizontalGroup(
            jpnPrincipalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipalMenuLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jpnPrincipalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnPrincipalMenuLayout.createSequentialGroup()
                        .addGap(0, 187, Short.MAX_VALUE)
                        .addComponent(btnGoBack)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogOut)
                        .addGap(25, 25, 25))
                    .addGroup(jpnPrincipalMenuLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpnPrincipalMenuLayout.setVerticalGroup(
            jpnPrincipalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPrincipalMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnPrincipalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpnPrincipalMenuLayout.createSequentialGroup()
                        .addGroup(jpnPrincipalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jpnPrincipalMenuLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel1)
                                .addGap(5, 5, 5)
                                .addGroup(jpnPrincipalMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLogOut)
                                    .addComponent(btnGoBack))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jpnPrincipalMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1536, 70));
        jpnPrincipalMenu.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(65, 80, 87));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnHelp.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnHelp.setText("Ayuda");

        timeLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setText("00:00:00");

        dateLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("lun, ene 01, 2000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1167, Short.MAX_VALUE)
                .addComponent(dateLabel)
                .addGap(18, 18, 18)
                .addComponent(timeLabel)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(timeLabel))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnHelp)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 810, 1540, 40));

        viewsSwitch.setBackground(new java.awt.Color(65, 80, 87));
        viewsSwitch.setPreferredSize(new Dimension(java.awt.Toolkit.getDefaultToolkit().getScreenSize().width, 780));
        viewsSwitch.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                viewsSwitchStateChanged(evt);
            }
        });

        mainMenu.setBackground(new java.awt.Color(65, 80, 87));

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        viewsSwitch.addTab("tab1", mainMenu);

        getContentPane().add(viewsSwitch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1540, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jpnPrincipalMenu);
        currentFrame.dispose(); // Cierra la ventana actual

        JFrame newFrame = new VwLogIn();
        newFrame.setVisible(true); // Abre la nueva ventana
        newFrame.setResizable(false);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnGoBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBackActionPerformed
        panelSwitch(new VwMainMenu(currentUser));
        btnGoBack.setEnabled(false);
    }//GEN-LAST:event_btnGoBackActionPerformed

    private void viewsSwitchStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_viewsSwitchStateChanged
        String name = "";
        if(viewsSwitch.getSelectedComponent() != null){
            name = viewsSwitch.getSelectedComponent().getName();
            btnGoBack.setEnabled(true);
            if(name == "MainMenu"){
                labMode.setText("Administración");
                txtViewPanel.setText("Menú Principal");
                btnGoBack.setEnabled(false);
            }
            if(name == "Customers"){
                labMode.setText("Administración");
                txtViewPanel.setText("Clientes");
            }
            if(name == "Vehicles"){
                labMode.setText("Administración");
                txtViewPanel.setText("Vehiculos");
            }
            if(name == "Repairs"){
                labMode.setText("Administración");
                txtViewPanel.setText("Reparaciones");
            }
            if(name == "Tickets"){
                labMode.setText("Administración");
                txtViewPanel.setText("Recibos");
            }
            if(name == "Incomes"){
                labMode.setText("Administración");
                txtViewPanel.setText("Ingresos");
            }
            if(name == "CustomersRegister"){
                labMode.setText("Registro");
                txtViewPanel.setText("Clientes");
            }
            if(name == "RepairsRegister"){
                labMode.setText("Registro");
                txtViewPanel.setText("Reparaciones");
            }
            if(name == "VehiclesRegister"){
                labMode.setText("Registro");
                txtViewPanel.setText("Vehiculos");
            }
            if(name == "TicketsRegister"){
                labMode.setText("Registro");
                txtViewPanel.setText("Tickets");
            }

        }
    }//GEN-LAST:event_viewsSwitchStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGoBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jpnPrincipalMenu;
    private javax.swing.JLabel labMode;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel txtViewPanel;
    private javax.swing.JTabbedPane viewsSwitch;
    // End of variables declaration//GEN-END:variables

private void panelSwitch(JPanel newPanel){
    viewsSwitch.removeAll();
    viewsSwitch.add(newPanel);
    viewsSwitch.setSelectedComponent(newPanel);
    newPanel.setSize(new java.awt.Dimension(viewsSwitch.getWidth(), viewsSwitch.getHeight()));
}
}
